#!/usr/bin/env python3.7.4
     
##############################################################################
# Argument Parsing
##############################################################################
import argparse, sys, os, re
sys.path.append(os.path.expanduser('~jmarulan/work_area/utils/environment/myPython/lib/python')); 
import cadence
argparser = argparse.ArgumentParser(description='Get libs from CDSLIB')
argparser.add_argument(dest='lib', type=str, help='Library in the cdslib')
args = argparser.parse_args()
##############################################################################
# Main Begins
##############################################################################
if os.getenv('CDSLIB'): cdsFile = os.getenv('CDSLIB')
else: cdsFile = os.getenv('WARD')+'/cds.lib'
if not os.path.isfile(cdsFile): raise IOError('CDSLIB variable not available')
cdsDt = cadence.readCds(cdsFile); 
libs = [lib for lib in filter(lambda ff: re.search(r''+args.lib,ff,flags=re.I),cdsDt.cds.keys())]
if not libs: print('No matching libraries: '+args.lib); exit()
tabSize = max(map(len,libs))
for lib in libs:
  print(lib.rjust(tabSize)+'   '+cdsDt.cds[lib])
exit()

