#!/bin/csh
##############################################################################
# Intel Top Secret							     #
##############################################################################
# Copyright (C) 2015, Intel Corporation.  All rights reserved.  	     #
#									     #
# This is the property of Intel Corporation and may only be utilized	     #
# pursuant to a written Restricted Use Nondisclosure Agreement  	     #
# with Intel Corporation.  It may not be used, reproduced, or		     #
# disclosed to others except in accordance with the terms and		     #
# conditions of such agreement. 					     #
#									     #
# All products, processes, computer systems, dates, and figures 	     #
# specified are preliminary based on current expectations, and are	     #
# subject to change without notice.					     #
##############################################################################
# Author:
#   Mauricio Marulanda
##############################################################################

# Python Help
if ($?{1} == "") then  ## check if you give an output
  echo 'Give one input morron'
else
  set pCmd = $1
  set module = `echo $pCmd | awk '{split($0,result,"."); print result[1]}'`
  if (${#argv} == 1) then ## if no second output print the whole thing
    echo "import $module; print dir($pCmd)" | python | sed -e 's/\[\|]//g' | sed -e 's/, /\n/g'
  else
    echo "import $module; print dir($pCmd)" | python | sed -e 's/\[\|]//g' | sed -e 's/, /\n/g' | grep $2
  endif
endif
