#!/usr/intel/bin/perl -w
##############################################################################
# Intel Top Secret							     #
##############################################################################
# Copyright (C) 2015, Intel Corporation.  All rights reserved.  	     #
#									     #
# This is the property of Intel Corporation and may only be utilized	     #
# pursuant to a written Restricted Use Nondisclosure Agreement  	     #
# with Intel Corporation.  It may not be used, reproduced, or		     #
# disclosed to others except in accordance with the terms and		     #
# conditions of such agreement. 					     #
#									     #
# All products, processes, computer systems, dates, and figures 	     #
# specified are preliminary based on current expectations, and are	     #
# subject to change without notice.					     #
##############################################################################
# Author:
#   Mauricio Marulanda
##############################################################################

# This script outputs the progress of a full-wave optimization.
# Expected input is a RIDE log file.

while (<>) {
  if (/^OPTIM-STEP> NT = ([\d\.Ee+-]+) OD = ([\d\.Ee+-]+) W = ([\d\.Ee+-]+) S = ([\d\.Ee+-]+)/) {
    printf "$1\t$2\t$3\t$4\t";
  } elsif (/^[=]+> Q \(full-wave\) =\s*([\d\.Ee+-]+) L \(full-wave\) =\s*([\d\.Ee+-]+)/) {
    printf "$1\t$2\n";
  }
}
