#!/usr/intel/bin/perl -w
##############################################################################
# Intel Top Secret							     #
##############################################################################
# Copyright (C) 2015, Intel Corporation.  All rights reserved.  	     #
#									     #
# This is the property of Intel Corporation and may only be utilized	     #
# pursuant to a written Restricted Use Nondisclosure Agreement  	     #
# with Intel Corporation.  It may not be used, reproduced, or		     #
# disclosed to others except in accordance with the terms and		     #
# conditions of such agreement. 					     #
#									     #
# All products, processes, computer systems, dates, and figures 	     #
# specified are preliminary based on current expectations, and are	     #
# subject to change without notice.					     #
##############################################################################
# Author:
#   Mauricio Marulanda
##############################################################################

use strict;
use Getopt::Long;

my %optctl;
&GetOptions(\%optctl, 'help');

if ($#ARGV == -1) {
  print "Usage: deembed <open> <short> <device>\n";
  exit 0;
}

my $file = $ARGV[2];

my $fileOpt = $file;
$fileOpt =~ s/.s2p$/_de.s2p/;

my $ride = "/nfs/site/eda/group/SYSNAME/tcad/RFDesigner/ride/ride";

print $fileOpt;

system "$ride -open = $ARGV[0] -short = $ARGV[1] -device = $ARGV[2] -output = $fileOpt";
